const arts = [
  {
    title: "Lizard People",
    image: "/artBox/cara_art.JPG",
    dimensions: "10in x 10in",
    medium: "Black ink on paper",
    yearMade: 2021,
    description: "about love",
    artistName: "Cara Dodge",
  },
  {
    title: "Bent Thru",
    image: "/artBox/cara_art2.JPG",
    dimensions: "10in x 10in",
    medium: "Black ink on paper",
    yearMade: 2021,
    description: "about love",
    artistName: "Cara Dodge",
  },
  {
    title: "Untitled",
    image: "/artBox/lucy_untitled.jpg",
    dimensions: "10in x 10in",
    medium: "Oil pastel on paper",
    yearMade: 2022,
    description: "A meticulously crafted masterpiece",
    artistName: "Lucy Blagg",
  },
  {
    title: "Shallow Copy",
    image: "/artBox/ShallowCopy.jpg",
    dimensions: "12in x 18in",
    medium: "Mixed media on paper",
    yearMade: 2021,
    description: "Beautifully crafted collage",
    artistName: "Lucy Blagg",
  },
  {
    title: "Octopus",
    image: "/artBox/Octopus.jpg",
    dimensions: "12in x 18in",
    medium: "Mixed media on paper",
    yearMade: 2021,
    description: "Beautifully crafted collage",
    artistName: "Lucy Blagg",
  },
  {
    title: "Dipping Hot Earth",
    image: "/artBox/Dipping_Hot_Earth.jpg",
    dimensions: "36in x 48in",
    medium: "Acrylic paint on canvas",
    yearMade: 2020,
    description: "Ambiguous butterfly motif leaving a scorched planet behind",
    artistName: "German Caceres",
  },
  {
    title: "Untitled",
    image: "/artBox/IMG_0011.JPG",
    dimensions: "36in x 48in",
    medium: "Acrylic paint on canvas",
    yearMade: 2020,
    description: "Golden, geometric angel",
    artistName: "German Caceres",
  },
  {
    title: "Sunflower",
    image: "/artBox/Sunflower.png",
    dimensions: "36in x 48in",
    medium: "Colored pencil on paper",
    yearMade: 2021,
    description: "Whimsical sunflower",
    artistName: "German Caceres",
  },
  {
    title: "Warpspeed (Sweet Angel)",
    image: "/artBox/Warpspeed_Sweet_Angel.jpg",
    dimensions: "36in x 48in",
    medium: "Acrylic paint on canvas",
    yearMade: 2020,
    description: "Angelic painting",
    artistName: "German Caceres",
  },
  {
    title: "Long Faces",
    image: "/artBox/nicoledrawing.jpg",
    dimensions: "12in x 18in",
    medium: "Ink on paper",
    yearMade: 2015,
    description: "A conglomerate of disturbing figures",
    artistName: "Nicole DeSantis",
  },
  {
    title: "Untitled",
    image: "/artBox/Yooboo_art.JPG",
    dimensions: "24in x 18in",
    medium: "Acrylic paint on canvas",
    yearMade: 2016,
    description: "Beautiful flowers in a field",
    artistName: "Yooboo Park",
  },
  {
    title: "Fallen",
    image: "/artBox/",
    dimensions: "8in x 10in",
    medium: "Black ink on paper",
    yearMade: 2021,
    description: "The sensual tension of desire; the piece tries to convey the assaulting energy of wanting.",
    artistName: "Cara Dodge",
  },
  {
    title: "Self-portrait",
    image: "/artBox/",
    dimensions: "8in x 10in",
    medium: "Black ink on paper",
    yearMade: 2021,
    description: "Artist's self portrait as a stereotype",
    artistName: "Cara Dodge",
  },
  {
    title: "Revelation",
    image: "/artBox/",
    dimensions: "8in x 10in",
    medium: "Black ink on paper",
    yearMade: 2021,
    description: "Inspired by the experience of divinity and the personal interaction of destiny.",
    artistName: "Cara Dodge",
  },
  {
    title: "Mirror",
    image: "/artBox/",
    dimensions: "8in x 10in",
    medium: "Black ink on paper",
    yearMade: 2021,
    description: "Artist's self-portrait on the uprooting nature of dysmorphia.",
    artistName: "Cara Dodge",
  },
  {
    title: "Prayers on a New Year",
    image: "/artBox/",
    dimensions: "8in x 10in",
    medium: "Black ink on paper",
    yearMade: 2021,
    description: "An experience of the movement of the universe on a day of transformation and celebration.",
    artistName: "Cara Dodge",
  },
  {
    title: "Nectar",
    image: "/artBox/",
    dimensions: "8in x 10in",
    medium: "Black ink on paper",
    yearMade: 2021,
    description: "Explorations of another world's flora and fauna.",
    artistName: "Cara Dodge",
  },
  {
    title: "Sometimes I Cannot Take This",
    image: "/artBox/",
    dimensions: "8in x 10in",
    medium: "Black ink on paper",
    yearMade: 2021,
    description: "Burden and hurt corrupting the body.",
    artistName: "Cara Dodge",
  },
  {
    title: "Wise-Men",
    image: "/artBox/",
    dimensions: "8in x 10in",
    medium: "Black ink on paper",
    yearMade: 2021,
    description: "Protective spirits that bring gifts.",
    artistName: "Cara Dodge",
  },
  {
    title: "Bulgarian Singers",
    image: "/artBox/",
    dimensions: "8in x 10in",
    medium: "Black ink on paper",
    yearMade: 2021,
    description: "An experience of Forest Park in Queens, NY where a group of Bulgarian folk singers performed amongst the pines between giant speakers",
    artistName: "Cara Dodge",
  },
  {
    title: "We've Come So Far",
    image: "/artBox/",
    dimensions: "8in x 10in",
    medium: "Black ink on paper",
    yearMade: 2021,
    description: "A reflection on the growth of spirit from 2018 to now",
    artistName: "Cara Dodge",
  },
  {
    title: "My Inheritance",
    image: "/artBox/",
    dimensions: "8in x 10in",
    medium: "Black ink on paper",
    yearMade: 2022,
    description: "My Inheritance is about family history of health, and the fear of dying like others before you",
    artistName: "Cara Dodge",
  },
  {
    title: "For My Brother",
    image: "/artBox/",
    dimensions: "8in x 10in",
    medium: "Black ink on paper",
    yearMade: 2022,
    description: "Dedicated to my brother, Domingo Castillo.",
    artistName: "Cara Dodge",
  },
];
const artists = [
  {
    name: "Cara Dodge",
    bio: "Cara Dodge is a multi-media & performance artist from Miami, Florida. They are co-founder of Theater of the Electric Mouth, a recent recipient of the O, Miami Poetry Grant, and current graduate of the Grace Hopper Program at Fullstack Academy.",
    website: "instagram.com/dedcooter",
  },
  {
    name: "Lucy Blagg",
    bio: "Lucy has been practicing art for several years. The fresh, sea air that she has the pleasure of experiencing in Rhode Island serves as her muse.",
    website: "www.lucy.com",
  },
  {
    name: "German Caceres",
    bio: "German Caceres is a multimedia artist from Miami, Florida. He is the co-creator of Midnight Thrift, “Miami’s first nightlife store”",
    website: "https://germancaceres.tumblr.com/work",
  },
  {
    name: "Nicole DeSantis",
    bio: "Nicole starting drawing at a young age and hasn't put the pencil down since. She is currently experimenting with watercolors.",
    website: "www.nicole.com",
  },
  {
    name: "Yooboo Park",
    bio: "Yooboo Park's art has received rave reviews across America. Crowds flock to see her latest work and she is very excited to share her work in Galleria!",
    website: "www.yooboo.com",
  },
];

module.exports = {
  arts,
  artists,
};
